config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where('id > ?', params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_message.html.haml
.chat-main__contents--message{data: {id: message.id}}
  .nickname
    .nickname__user 
      = message.user.name
    .nickname__time
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  .comment
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_sideber.html.haml
.sideber
  .sideber__user
    %h3.user-name
      = current_user.name
    .user-menu
      .user-menu__edit-user
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      .user-menu__new-group
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .sideber__group
    - current_user.groups.each do |group|
      .sideber__group--name
        = link_to group_messages_path(group) do
          .group-name
            = group.name
          .group-message
            = group.show_last_message

app/views/messages/index.html.haml
= render partial: 'sideber'

.chat-main
  .chat-main__header
    .chat-main__header--group
      %p.samplegroup
        =@group.name
      %ul.member
        Member: 
        - @group.users.each do |user|
          %li.member-list
            = user.name
    .edit
      = link_to "edit", edit_group_path(@group)
  .chat-main__contents
    = render @messages
  .form
    = form_for [@group, @message] do |f|
      .input-box
        = f.text_field :content, class: 'form-message', placeholder: 'type a message'
        = f.label :image, class: 'image-label' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form-submit'